# Experiment  8: Tools Used in EDA

### Name: Lehalyaa L
### PRN: 25070123176
### Batch: ENTC - A2

In [3]:
# Declaration of Numpy

import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([[1, 2, 3], [4, 5, 6]])

print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [7]:
# Dimension of Array

print("Dimension of array A is: ", a.ndim)
print("Dimension of array  B is: ", b.ndim )

Dimension of array A is:  1
Dimension of array  B is:  2


In [10]:
# Shape of an Array

print("Dimension of A: ", a.shape)
print("Dimension of B: ", b.shape)

Dimension of A:  (4,)
Dimension of B:  (2, 3)


In [11]:
# Data type of elements in an array

print("The data type of elements in A is", a.dtype)
print("The data type of elements in B is", b.dtype)

The data type of elements in A is int64
The data type of elements in B is int64


## In - Built Functions in NumPy

In [13]:
# Printing a Zero Matrix

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# Printing an Identity Matrix

np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
# Diagonal matrix

np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# printing a range of range with Step Size

np.arange(1,11,2) # Same as range function, stop value is not included

array([1, 3, 5, 7, 9])

In [19]:
# dividing a number into specified terms

np.linspace(0,1,5) # 1 is also included


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
# Arithmetic oprations in Arrays

c = a * 2
d = a + 5
print(c, "\n")
print (d)

[20 40 60 80] 

[15 25 35 45]


In [23]:
# Mean of elements in an array

print("The average of elements in A is: ",np.mean(a))
print("The average of elements in B is: ",np.mean(b))

The average of elements in A is:  25.0
The average of elements in B is:  3.5


In [24]:
# Median of elements

print("Median of A: ",np.median(a))
print("Median of B: ", np.median(b))

''' For clean data mean and median are same, if different take the value of
median which is more appropriate'''

Median of A:  25.0
Median of B:  3.5


In [29]:
# Aggregate Functions

print("Operations performed in Matrix A")
print("Max of A: ",np.max(a))
print("Min of A: ",np.min(a))
print("Sum of A: ",np.sum(a), "\n")


print("Operations Performed in Matrix B")
print("MAx of B: ", np.max(b))
print("Min of B: ", np.min(b))
print("Sum of B: ", np.sum(b))

Operations performed in Matrix A
Max of A:  40
Min of A:  10
Sum of A:  100 

Operations Performed in Matrix B
MAx of B:  6
Min of B:  1
Sum of B:  21
